#!/bin/bash
APP="pinky"
TEST_DIR="test"

TESTS=$(find $APP/$TEST_DIR -maxdepth 1 -name 'test_*.py')
coverage run $(which trial) $TESTS || exit $?
coverage report --include="$APP/*" --omit="$APP/$TEST_DIR/*"
# coverage html -d $APP/$TEST_DIR/reports --include="$APP/*" --omit="$APP/$TEST_DIR/*"
