#!/bin/bash

APP="pinky"
TEST_DIR="test"

function clean {
    echo "Clearing .pyc files"
    find . -name "*.pyc" -exec rm -rf {} \;
}

function exec_coverage {
    coverage run $(which trial) $APP || exit $?
    coverage report --include="$APP/*" --omit="$APP/$TEST_DIR/*"
    # coverage html -d $APP/$TEST_DIR/reports --include="$APP/*" --omit="$APP/$TEST_DIR/*"
}

clean;
exec_coverage;
clean;
